Task_1_1_1
AntonTsoy/OOP pull request #11
Opened 2023-09-13 06:38 UTC by AntonTsoy

New attempt

2023-09-13 09:57 UTC, IgorShal commented
Pretty good solution

2023-09-14 14:15 UTC, galinabykova requested changes

2023-09-14 14:15 UTC, galinabykova commented on Task_1_1_1/src/main/java/.gitignore
А зачем тебе нужен этот файл тут? Он должен лежать в корне проекта
И что ты хотел им заигнорить?

2023-09-14 14:15 UTC, galinabykova commented on Task_1_1_1/src/main/java/Heap.java
> +    public Heap(int[] array) {
Лучше сделать передачу параметра в метод сортировки, и чтобы тот возвращал отсортированный массив. Такое использование не очень удобно

2023-09-14 14:15 UTC, galinabykova commented on Task_1_1_1/src/main/java/Heap.java
> +            siftDown(arrayLength, largestNodeId);
Java не оптимизирует хвостовую рекурсию, либо переделай в цикл, чтобы не было переполнения стека, либо докажи мне, что здесь не будет переполнения стека

2023-09-14 14:15 UTC, galinabykova commented on Task_1_1_1/src/main/java/.gitignore
для чего этот файл?

2023-09-14 14:34 UTC, AntonTsoy commented on Task_1_1_1/src/main/java/.gitignore
я компилировал и исполнял CheckSort.java отдельно от всего проекта, поэтому в той директории появлялись .class файлы, чтобы они не попали в репозиторий я написал .gitignore

2023-09-14 14:34 UTC, AntonTsoy commented on Task_1_1_1/src/main/java/.gitignore
сейчас все уберу и исправлю

2023-09-14 14:37 UTC, galinabykova commented on Task_1_1_1/src/main/java/.gitignore
А, хорошо)

2023-09-14 15:11 UTC, AntonTsoy commented on Task_1_1_1/src/main/java/Heap.java
> +            siftDown(arrayLength, largestNodeId);
Я уже начал переписывать эту функцию, чтобы не использовать рекурсию. Но все-таки попытаюсь объяснить, почему переполнения не будет. Асимптотика этой функции log2 N (N - длина массива). Нужен неприлично большой массив, чтобы случилось переполнение стека

2023-09-18 06:30 UTC, galinabykova approved these changes

2023-09-18 06:34 UTC, merged