Task_1_2_1
AntonTsoy/OOP pull request #13
Opened 2023-10-16 01:47 UTC by AntonTsoy

2023-10-16 05:26 UTC, galinabykova requested changes

2023-10-16 05:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/tree/DfsIterable.java
> +    private class DfsIterator implements Iterator<T> {  // Can I make this class STATIC?
если ты сделаешь static, ты потеряешь доступ к нестатическим полям внешнего класса. Кажется, ты этого не хочешь

2023-10-16 05:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/tree/Tree.java
> +     * @return true if this object is the same as the obj argument; false otherwise.
деревья можно сравнивать по-разному, и из твоей спецификации непонятно, что такое равные деревья в твоей реализации

2023-10-16 05:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/tree/BfsIterable.java
> +            if (currentNode.getNodeValue() == null) {
можешь описать, как работает твой отлов ConcurrentModificationException?

2023-10-16 05:26 UTC, galinabykova commented on Task_1_2_1/src/main/java/tree/BfsIterable.java
> +            if (currentNode.getNodeValue() == null) {
не увидела тест, который проверяет, что ConcurrentModificationException бросается, если его нет, сделай, пожалуйста

2023-10-16 06:54 UTC, AntonTsoy commented on Task_1_2_1/src/main/java/tree/DfsIterable.java
> +    private class DfsIterator implements Iterator<T> {  // Can I make this class STATIC?
да, я такого не хочу, просто хотел порассуждать, какие модификаторы доступа можно вешать на приватные подклассы

2023-10-16 07:03 UTC, AntonTsoy commented on Task_1_2_1/src/main/java/tree/Tree.java
> +     * @return true if this object is the same as the obj argument; false otherwise.
Деревья будут эквиваленты, если у них одно и то же значение и если их дети имеют одни и те же значения и находятся в одном и том же порядке. И два условия выше также индуктивно должны выполнятся для детей данного дерева-вершины

2023-10-16 07:08 UTC, AntonTsoy commented on Task_1_2_1/src/main/java/tree/BfsIterable.java
> +            if (currentNode.getNodeValue() == null) {
В моей реализации у дерева не может быть значения Null при создании. Значение Null оно приобретает только после того, как оно было удалено. Когда идем по дереву for each-ем, вершины по которым мы должны пройтись постепенно попадают в очередь. Если вершина из очереди имеет значение Null, значит оно было удалено из дерева. И так как вершина все таки попала в нашу очередь и мы должны были пройтись по ней во время for each-а, следовательно её удалили во время итерации. Значит бросаем Exception

2023-10-16 07:15 UTC, galinabykova commented on Task_1_2_1/src/main/java/tree/Tree.java
> +     * @return true if this object is the same as the obj argument; false otherwise.
Здорово, добавь это в спецификацию, чтобы пользователям было понятно, как это работает

2023-10-16 07:27 UTC, galinabykova commented on Task_1_2_1/src/main/java/tree/DfsIterable.java
> +    private class DfsIterator implements Iterator<T> {  // Can I make this class STATIC?
вложенные классы в целом делят на nested и inner как раз по модификатору static, так что здорово, что у тебя возник этот вопрос. Мне не приходит идей о том, как приватность влияет на это, разве что inner класс даже без private нельзя было бы создать отдельно от внешнего класса.

2023-10-16 07:32 UTC, galinabykova commented on Task_1_2_1/src/main/java/tree/BfsIterable.java
> +            if (currentNode.getNodeValue() == null) {
а добавление в процессе итерирования ты разрешаешь?

2023-10-16 08:22 UTC, AntonTsoy commented on Task_1_2_1/src/main/java/tree/BfsIterable.java
> +            if (currentNode.getNodeValue() == null) {
добавление у меня не порождает исключение. А это нужно?

2023-10-16 15:20 UTC, galinabykova commented on Task_1_2_1/src/main/java/tree/BfsIterable.java
> +            if (currentNode.getNodeValue() == null) {
не обязательно, но ты должен подумать о том, как в в этом случае будет вести себя коллекция и почему ты считаешь, что в этом случае пользователь ничего не сломает

2023-10-17 02:43 UTC, AntonTsoy commented on Task_1_2_1/src/main/java/tree/Tree.java
> +     * @return true if this object is the same as the obj argument; false otherwise.
добавил в спецификацию

2023-10-17 02:44 UTC, AntonTsoy commented on Task_1_2_1/src/main/java/tree/BfsIterable.java
> +            if (currentNode.getNodeValue() == null) {
добавил тесты, которые проверяют вызов ConcurrentModificationException

2023-10-17 03:43 UTC, galinabykova requested changes
reviewdog

2023-10-17 05:03 UTC, galinabykova approved these changes

2023-10-17 08:21 UTC, merged