Task_1_3_1
AntonTsoy/OOP pull request #14
Opened 2023-11-08 17:01 UTC by AntonTsoy

2023-11-08 18:37 UTC, galinabykova requested changes
reviewdog ещё)

2023-11-08 18:37 UTC, galinabykova commented on Task_1_3_1/src/main/java/substring/SubStringSearch.java
> +            System.out.println(e.getMessage());
у тебя тут странненько, если поймается исключение, выведется сообщение об ошибке и дальше код пойдёт. Скорее всего где-то дальше случится новое исключение, так как файл не открылся. Сообщение в stdout легко не заметить, можно не сразу понять, где случилась ошибка. Поэтому тут лучше дальше пробросить исключение. Кстати такие ошибки, если их надо вывести, лучше писать в stderr

2023-11-12 08:37 UTC, AntonTsoy commented on Task_1_3_1/src/main/java/substring/SubStringSearch.java
> +            System.out.println(e.getMessage());
Исправил

2023-11-12 12:00 UTC, galinabykova requested changes

2023-11-12 12:00 UTC, galinabykova commented on Task_1_3_1/src/main/java/substring/SubStringSearch.java
> +            throw new RuntimeException(e);
с этой штукой тоже есть проблема, потому что по соглашению RuntimeException не надо ловить. Это такая мягкая версия exit(-1). Здесь на самом деле можно не ловить исключение или бросить новое с уточнённой информацией о проблеме, если это возможно (но не RuntimeException)

2023-11-12 12:00 UTC, galinabykova commented on Task_1_3_1/src/test/java/substring/TestSubStringSearch.java
> +            for (int i = 1024 * 1024; i > 1; i /= 2) {
не очень понятно, почему оно так, похоже на какую-то ошибку, допущенную при отладке. В цикле i никак не используется, кажется, что это то же самое, что for(int i = 0; i < 20; ++i).

2023-11-12 12:00 UTC, galinabykova commented on Task_1_3_1/src/test/java/substring/TestSubStringSearch.java
> +            for (int i = 1024 * 1024; i > 1; i /= 2) {
а, я поняла, ты хочешь добиться увеличения длины строки в 1024 * 1024 раз. Нельзя ли это как-то сделать более читаемо? Дать другое название индексу i, и может быть иначе менять счётчик

2023-11-13 08:50 UTC, AntonTsoy commented on Task_1_3_1/src/main/java/substring/SubStringSearch.java
> +            throw new RuntimeException(e);
Но тут я и не пытаюсь ловить Runtime. Я ловлю IOException, но бросаю Runtime. 
Я полазил в документации Runtime там не было ничего написано ни про его ловлю, ни про бросание. Была такая фраза: <<RuntimeException and its subclasses are unchecked exceptions. Unchecked exceptions do not need to be declared in a method or constructor's throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.>>
Но как я понял она означает, что просто в сигнатуре метода не нужно писать throws RuntimException, если метод где-то внутри его бросает. 
Еще такая деталь - я читал документацию для Java 20, хотя сам пишу на Java 17

2023-11-13 09:00 UTC, AntonTsoy commented on Task_1_3_1/src/main/java/substring/SubStringSearch.java
> +            throw new RuntimeException(e);
Ещё во всех примерах обработки IOException со StackOverflow, в которых программа прекращала выполнение вместо мягкой обработки этой ошибки, я видел либо return <что-то плохое>, либо throw new RuntimeException

2023-11-13 09:02 UTC, AntonTsoy commented on Task_1_3_1/src/test/java/substring/TestSubStringSearch.java
> +            for (int i = 1024 * 1024; i > 1; i /= 2) {
В этом случае for заменил на while. Дал переменной для итерации более понятное имя. Добавил комментарии к этапам записи в файл 8-ми гигабайтов

2023-11-13 09:47 UTC, galinabykova commented on Task_1_3_1/src/main/java/substring/SubStringSearch.java
> +            throw new RuntimeException(e);
Ага, именно для этого используется обычно RuntimeException. Ситуация, когда ничего уже сделать нельзя, и надо прекращать работу. Является ли такой ситуацией ошибка при открытии файла? Мне кажется, нет, но это лучше обсудить при очной сдаче)

2023-11-13 09:48 UTC, galinabykova approved these changes

2023-11-13 09:58 UTC, merged