Task_1_4_1
AntonTsoy/OOP pull request #15
Opened 2023-11-21 13:33 UTC by AntonTsoy

2023-11-21 16:57 UTC, galinabykova requested changes
reviewdog

2023-11-21 16:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    private int currentSemester;   // The number of the current semester.
ты называешь семестром и номер семестра, и оценки за семестр. Это немного запутывает при чтении кода. Мне кажется, лучше уточнить в названии этой переменной, что это именно номер

2023-11-21 16:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/examBook/Semester.java
> +        if (newSubject.getMark() < 4) {
а какую оценку ставят за дифференциальный зачёт? не будет ли тут из-за этого проблем?

2023-11-21 16:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    public double getCurrentAverageMark() {
при расчёте среднего значения берётся последняя оценка за предмет. То есть, если у тебя были алгоритмы в 1 и во 2 семестре, а в других их не было, то в расчёте средней участвует только оценка за второй семестр

2023-11-21 16:57 UTC, galinabykova commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    public double getCurrentAverageMark() {
ещё этот метод надо написать через StreamAPI без циклов и с минимальным использованием forEach из StreamAPI, это сделает эту функцию более читаемой, а ещё ты потренируешься пользоваться StreamAPI

2023-11-21 17:21 UTC, galinabykova commented on Task_1_4_1/src/main/java/examBook/Semester.java
> +        if (newSubject.getMark() < 4) {
ой, я перепутала диф зачёт с зачётом

2023-11-21 17:47 UTC, AntonTsoy commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    private int currentSemester;   // The number of the current semester.
Нет, все поля для оценок я называю mark, все целочисленные поля в названии, которых semester - номер семестра

2023-11-21 17:51 UTC, AntonTsoy commented on Task_1_4_1/src/main/java/examBook/Semester.java
> +        if (newSubject.getMark() < 4) {
этот момент мы с тобой уже обсуждали, ты сказала, что о недифференцированных зачетах можно не думать

2023-11-21 18:15 UTC, galinabykova commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    private int currentSemester;   // The number of the current semester.
криво сформулировала, я имею ввиду, что у тебя есть сущность Semestr, а есть целочисленные переменные, которые немного про другое, и они тоже semestr

Вот такой код
`new Semester(++currentSemester)`
непонятен.

Лучше стараться избегать использование одного термина для разных сущностей. В групповой разработке это очень путает.

2023-11-25 02:10 UTC, AntonTsoy commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    private int currentSemester;   // The number of the current semester.
исправил

2023-11-25 02:11 UTC, AntonTsoy commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    public double getCurrentAverageMark() {
исправил

2023-11-25 02:12 UTC, AntonTsoy commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    public double getCurrentAverageMark() {
Переписал со Stream API, forEach вообще не использовал, но не думаю, что функция стала более читаемой

2023-11-25 10:02 UTC, galinabykova commented on Task_1_4_1/src/main/java/credit/ExamBook.java
> +            && diplomaMarks().stream().mapToInt(a -> a).sum() / diplomaMarks().size() > 4.75
кажется, тут можно использовать average вместо sum / size

2023-11-25 10:02 UTC, galinabykova commented on Task_1_4_1/src/main/java/credit/ExamBook.java
> +        return currentHalfIdx == 8 && !diplomaMarks().contains(2) && !diplomaMarks().contains(3)
кажется, что лучше один раз посчитать diplomaMarks, потому что метод diplomaMarks достаточно тяжёлый

2023-11-25 10:02 UTC, galinabykova commented on Task_1_4_1/src/main/java/credit/ExamBook.java
> +                .mapToObj(idx -> half.getSubject(idx)))
```
IntStream.range(1, half.quantityOfSubjects() + 1)  
                .mapToObj(idx -> half.getSubject(idx)
```
Кажется, вместо этого можно сделать метод GetSubjectStream в Semestr. Этот метод будет просто обёрткой над коллекцией дисциплин

2023-11-25 10:02 UTC, galinabykova commented on Task_1_4_1/src/main/java/examBook/ExamBook.java
> +    public double getCurrentAverageMark() {
Привет, добавила небольшие замечания по используемым функциям, надеюсь, что после их исправления станет чуть более читаемо, чем сейчас. StreamAPI действительно делают код более читаемым иногда, хотя это не единственная причина их использования. Если забыть о том, что мне нужно было, что бы вы потренировались использовать StreamAPI, может быть, тут я впала в крайность

2023-11-25 10:02 UTC, galinabykova approved these changes

2023-11-25 10:03 UTC, galinabykova commented on Task_1_4_1/src/main/java/credit/ExamBook.java
> +                .mapToObj(idx -> half.getSubject(idx)))
и вместо этого куска кода ты просто напишешь Semestr.GetSubjectStream()

2023-11-25 10:39 UTC, AntonTsoy commented on Task_1_4_1/src/main/java/credit/ExamBook.java
> +        return currentHalfIdx == 8 && !diplomaMarks().contains(2) && !diplomaMarks().contains(3)
если честно я пытался так делать, только тогда начинало вылазить сообщение о выходе за границы массива. Как я понял нельзя по одному потоку пройтись дважды

2023-11-25 10:39 UTC, AntonTsoy commented on Task_1_4_1/src/main/java/credit/ExamBook.java
> +            && diplomaMarks().stream().mapToInt(a -> a).sum() / diplomaMarks().size() > 4.75
исправил, сейчас запушу

2023-11-25 10:52 UTC, merged

2023-11-25 13:41 UTC, galinabykova commented on Task_1_4_1/src/main/java/credit/ExamBook.java
> +        return currentHalfIdx == 8 && !diplomaMarks().contains(2) && !diplomaMarks().contains(3)
О, правда. Может быть, если что-то очень тяжёлое, можно сохранить в коллекцию, и её потом преобразовывать в поток, когда она понадобится.