Task_1_2_2
AntonTsoy/OOP pull request #17
Opened 2023-12-23 09:11 UTC by AntonTsoy

2023-12-23 13:03 UTC, galinabykova requested changes

2023-12-23 13:03 UTC, galinabykova commented on Task_1_2_2/src/main/java/graph/Graph.java
> +public interface Graph<L extends Number, N> {
здорово, что ты указал, что веса ребра должны быть именно Number

2023-12-23 13:03 UTC, galinabykova commented on Task_1_2_2/src/main/java/graph/Graph.java
> +public interface Graph<L extends Number, N> {
в этом вопросе, скорее всего, не надо ничего менять в коде, нужно просто хорошо подумать, может быть, поэкспериментировать,  и ответить. Предположим, что пользователь нашей библиотеки хочет использовать наши алгоритмы, но своё представление графа. Graph это публичный интерфейс, поэтому он может создать класс, которые реализует методы Graph в своём пакете, а потом объект этого класса передать в sortDijkstra. Но методы интерфейса имеют пакетную видимость. Сможем ли мы вызвать методы пользовательского графа в нашем sortDijkstra? Нужно ли будет пользователю менять что-то в сигнатуре методов интерфейса, например, расширять область видимости? И сможет ли он это сделать?

2023-12-23 13:03 UTC, galinabykova commented on Task_1_2_2/src/main/java/graph/AdjacencyList.java
> +     * Adds a new edge to the graph with the specified name, length, and start and end vertices.
кажется, эта спецификация дублирует спецификацию из интерфейса. Мне кажется, здесь такая же проблема, как и с дублированием кода, высока вероятность, что при изменении поведения, ты изменишь документацию в интерфейсе, но забудешь поменять её здесь. Мне кажется, тут лучше указать, метод из какого интерфейса ты реализуешь, описать особенности конкретно этой реализации, если они есть, и сослаться на документацию интерфейса, но тут ты можешь со мной поспорить. В документации по java я не видела полное копирование документации из родительского класса, но бывало, что часть дублировалась.

Посмотри, например, как это делается в документации java
https://docs.oracle.com/javase/8/docs/api/java/util/List.html#hashCode--

2023-12-23 13:03 UTC, galinabykova commented on Task_1_2_2/src/main/java/graph/Edge.java
> +            throw new IllegalArgumentException("Len can't be ZERO");
а почему вес не может быть нулевым в твоей реализации?

2023-12-23 13:03 UTC, galinabykova commented on Task_1_2_2/src/test/java/graph/TestGraphs.java
> +    void testResourceD(Graph<Double, String> graph) throws IOException {
не сразу понятно, что D - это Дейкстра. Лучше всё-таки полностью прописать название алгоритма. Вдруг в будущем ещё алгоритм на D появится

2023-12-23 15:47 UTC, AntonTsoy commented on Task_1_2_2/src/main/java/graph/AdjacencyList.java
> +     * Adds a new edge to the graph with the specified name, length, and start and end vertices.
Там где у реализации метода есть какие-то особенности, я расширил спецификацию

2023-12-23 15:48 UTC, AntonTsoy commented on Task_1_2_2/src/main/java/graph/Edge.java
> +            throw new IllegalArgumentException("Len can't be ZERO");
Когда я начинал писать лабу, я не думал о работе с отрицательными ребрами, думал только о ребрах с положительной длинной. Поэтому мне казалось, что если у ребра нулевая длинна, это то же самое, что ребра просто нет. Но сейчас я понимаю, что те рассуждения были ошибочными

2023-12-23 15:49 UTC, AntonTsoy commented on Task_1_2_2/src/test/java/graph/TestGraphs.java
> +    void testResourceD(Graph<Double, String> graph) throws IOException {
Исправил

2023-12-23 15:51 UTC, AntonTsoy commented on Task_1_2_2/src/main/java/graph/Graph.java
> +public interface Graph<L extends Number, N> {
Я попрактикуюсь с этим

2023-12-23 17:51 UTC, galinabykova requested changes
reviewdog

2023-12-24 14:08 UTC, galinabykova approved these changes

2023-12-31 16:32 UTC, merged