Task_2_1_1
AntonTsoy/OOP pull request #18
Opened 2024-02-17 16:46 UTC by AntonTsoy

2024-02-18 06:02 UTC, galinabykova requested changes

2024-02-18 06:02 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +            throw new RuntimeException("It's stupid to create zero and less number of threads!");
я подозреваю, что здесь бросается RuntimeException, потому что ты не хотел менять сигнатуру метода ради одной реализации интерфейса. Если это так, можно эту проверку вынести в конструктор и бросить там проверяемое исключение. Если нет, напиши, почему ты бросаешь здесь именно RuntimeException

2024-02-18 06:02 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +                    // https://stackoverflow-com.translate.goog/questions/6546193/how-to-catch-an-exception-from-a-thread?_x_tr_sl=en&_x_tr_tl=ru&_x_tr_hl=ru&_x_tr_pto=sc
такие комментарии лучше убрать)

2024-02-18 06:02 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +    private Integer[] numbers;
это поле тоже можно сделать final

2024-02-18 06:02 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/SequentialDetector.java
> +            }
тут можно StreamAPI использовать

2024-02-18 06:02 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/PrimeNumbersDetector.java
> + * Интерфейс, который должны реализовывать оба решения - последовательное и параллельное.
тут лучше добавить описание задачи

2024-02-18 06:02 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +            // тут главный поток ждёт, но можно его тоже загрузить
и этот комментарий тоже надо убрать

2024-02-18 06:02 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/PrimeNumbersDetectorUtils.java
> +    static boolean isPrimeNumber(Integer number) {
Почему ты решил использовать здесь Integer, а не int? (просто вопрос, мне интересна твоя мотивация)

2024-02-20 03:22 UTC, AntonTsoy commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +    private Integer[] numbers;
Там нельзя было поставить `final`, моя задумка этому мешала. Сейчас я решил, что лучше просто убрать это поле

2024-02-20 03:26 UTC, AntonTsoy commented on Task_2_1_1/src/main/java/multithreading/PrimeNumbersDetectorUtils.java
> +    static boolean isPrimeNumber(Integer number) {
Тут я чего-то особенного не задумывал. Просто эта функция в моём коде должна была применяться элементам массива `Integer[]`, то есть к `Integer`-ам, поэтому тип параметра так указал. А про `int` я просто не задумался

2024-02-20 05:01 UTC, AntonTsoy commented on Task_2_1_1/src/main/java/multithreading/SequentialDetector.java
> +            }
добавил

2024-02-20 05:11 UTC, AntonTsoy commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +            throw new RuntimeException("It's stupid to create zero and less number of threads!");
исправил

2024-02-21 07:09 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +            throw new RuntimeException("It's stupid to create zero and less number of threads!");
а почему RuntimeException?)

2024-02-21 07:09 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/PrimeNumbersDetectorUtils.java
> +    static boolean isPrimeNumber(Integer number) {
@AntonTsoy а почему ты решил использовать Integer[], а не int[]?

2024-02-21 07:21 UTC, galinabykova requested changes
reviewdog и ещё оставила комментарии) не заметила вчера, что ты запросил ревью, прости(

2024-02-23 04:48 UTC, AntonTsoy commented on Task_2_1_1/src/main/java/multithreading/PrimeNumbersDetectorUtils.java
> +    static boolean isPrimeNumber(Integer number) {
Изначально я об этом не думал, и почему-то на автомате решил использовать `Integer`. Сегодня я стал думать о том можно ли с `Integer` перейти на `int` и станет ли от этого программа лучше. 

Первое с чем я столкнулся это усложнение работы со Stream-ами при последовательном и параллельном решении. На сколько я помню мы Stream-ы можем применять только к коллекциям. А из этого уже появляется необходимость так или иначе использовать `Integer` - для создания коллекции. Я пытался гуглить создаётся ли у нас новый объект при боксинге из `int` в `Integer` и насколько я понял - да, создаётся. Поэтому если мы изначально будем работать с `int`, то нам придется расходовать дополнительную память под объекты `Integer`. 

Поэтому я решил оставить все как есть.

2024-02-23 05:14 UTC, AntonTsoy commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +            throw new RuntimeException("It's stupid to create zero and less number of threads!");
Я тогда просто перенёс код в конструктор. Я поискал существующие в Java проверяемые исключения, подходящие под этот случай, таких не нашёл. Понял, что нужно писать своё исключение, но решил просто взять подходящее непроверяемое

2024-02-23 13:26 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +            throw new RuntimeException("It's stupid to create zero and less number of threads!");
@AntonTsoy а вот это не подойдёт?
https://docs.oracle.com/javase/8/docs/api/java/lang/IllegalArgumentException.html

2024-02-23 13:27 UTC, galinabykova commented on Task_2_1_1/src/main/java/multithreading/ThreadedDetector.java
> +            throw new RuntimeException("It's stupid to create zero and less number of threads!");
а, увидела)

2024-02-23 13:29 UTC, galinabykova approved these changes

2024-02-23 13:37 UTC, merged