Task_2_2_1
AntonTsoy/OOP pull request #19
Opened 2024-04-09 18:43 UTC by AntonTsoy

2024-04-10 07:30 UTC, galinabykova requested changes
Привет, хорошее первое решение) правильно ли я поняла, что заказы и пиццы в складе при остановке сериализуются, при этом заказы и пиццы, которые были в этот момент в процессе готовки/доставки, теряются?

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/BlockingDesk.java
> +        if (this.limit > 0) {
я тут не сразу поняла, что это проверка на существование лимита у очереди. Можно сравниться с -1 (для которой стоит завести переменную, потому что сейчас эта магическая константа)

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/BlockingDesk.java
> +        if (this.limit > 0) {
или можно, например, поставить лимит в максимальный int, если лимита нет

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/BlockingDesk.java
> +    public synchronized boolean isEmpty() {
вот этот метод может ввести пользователя в заблуждение, надо указать с документации (и лучше в названии), что он может возвращать устаревшую информацию

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/BlockingDesk.java
> +    public synchronized int size() {
тут метод может ввести пользователя в заблуждение, надо указать с документации (и лучше в названии), что он может возвращать устаревшую информацию

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Order.java
> +public class Order {
кажется, это можно было бы сделать через enum, создав в нём кастомное поле сообщения

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Order.java
> +        }
вот тут мне не очень понятно, почему эта проверка в этом методе (неочевидно, что она тут) и есть ощущение, что ты тут пытаешься использовать исключение не для исключительных ситуаций. InterruptedException бросается обычно в блокирующих методах про что угодно, и там как-то естественно его бросать, а тут не уверена, что его стоит бросать

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Order.java
> +        }
https://docs.oracle.com/javase/8/docs/api/java/lang/InterruptedException.html

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Chef.java
> +                this.currOrder.prevState();
ты тут опираешься на знание, что nextState сначала поменяет состояние, а потом бросит исключение.  Можно сказать, что у тебя тут абстракция протекает)

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Chef.java
> +                    " не успел завершить заказ и выкинул остатки.");
мило)

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Chef.java
> +                    " слишком долго ждал, когда склад освободится, поэтому оставил пиццу себе");
идеальные условия работы)

2024-04-10 07:30 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Pizzeria.java
> +            System.err.println("Налоговая на законно закрыла пиццерию!!!");
(

2024-04-16 17:13 UTC, galinabykova requested changes

2024-04-16 17:13 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Chef.java
> +            throw new RuntimeException();
расскажи на очной защите, почему RuntimeException)

2024-04-16 17:13 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Chef.java
> +            logger.info(this + " повар взял заказ: " + currOrder);
для пиццерии такое описание событий выглядит чудесно, но вот сейчас подумала, что оно немного напоминает проблему с чрезмерным логгированием. Исправлять не надо, но на практике, с одной стороны, нужно логгировать достаточно, чтобы потом понять, что пошло не так, но с другой стороны - не надо перебарщивать, чтобы потом можно было найти ту самую строчку, где всё пошло не так

2024-04-16 17:13 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/Chef.java
> +            logger.info(this + " повар взял заказ: " + currOrder);
хотя у тебя, наверно, скорее дело в том, что текста много. Логгировать изменение состояния заказа достаточно естественно

2024-04-16 17:13 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/WorkerFactoryPizzeria.java
> +    public Thread hireWorker(Worker worker) {
О, рефлексия

2024-04-16 17:13 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/WorkerFactoryPizzeria.java
> +    public Thread hireWorker(Worker worker) {
тут лучше бы instance of использовать

2024-04-16 17:13 UTC, galinabykova commented on Task_2_2_1/src/main/java/pizzeria/WorkerFactoryPizzeria.java
> +    public Thread hireWorker(Worker worker) {
вот это исправь

2024-04-17 13:00 UTC, AntonTsoy commented on Task_2_2_1/src/main/java/pizzeria/Chef.java
> +            logger.info(this + " повар взял заказ: " + currOrder);
ок, понял

2024-04-17 13:14 UTC, AntonTsoy commented on Task_2_2_1/src/main/java/pizzeria/Chef.java
> +            throw new RuntimeException();
ок, попытаюсь объяснить, но сейчас решил его убрать

2024-04-20 07:31 UTC, galinabykova approved these changes

2024-04-20 14:34 UTC, merged