Task_2_3_1
AntonTsoy/OOP pull request #20
Opened 2024-04-30 15:47 UTC by AntonTsoy

2024-05-02 05:13 UTC, galinabykova requested changes
змейка красивая) напиши, какой паттерн будешь использовать

2024-05-02 05:13 UTC, galinabykova commented on Task_2_3_1/src/main/java/fxlab/snake/hello/HelloApplication.java
> +                throw new RuntimeException(e);
вот тут ситуация, которую мы с тобой обсуждали во вт)

2024-05-02 05:13 UTC, galinabykova commented on Task_2_3_1/src/main/java/fxlab/snake/hello/HelloApplication.java
> +        for (int i = 0; i < 24; i++) {
лучше константам дать имена

2024-05-02 05:13 UTC, galinabykova commented on Task_2_3_1/src/main/resources/fxlab/snake/hello/hello-view.fxml
> +    <Label fx:id="welcomeText"/>
вот тут было бы хорошо забиндить переменную, чтобы не нужно было в onHelloButtonClick самому обращаться к welcomeText

2024-05-02 05:13 UTC, galinabykova commented on Task_2_3_1/src/main/java/fxlab/snake/Main.java
в этом классе смешаны модель и представление. Модель нужно отдельно вынести

2024-05-07 18:23 UTC, galinabykova approved these changes

2024-05-07 18:23 UTC, galinabykova commented on Task_2_3_1/src/main/java/fxlab/snake/model/Snake.java
> +    private List<Point> snakeBody;
мне кажется, что это змейку можно было в отдельный компонент вынести (в смысле тело змейки)

2024-05-07 18:23 UTC, galinabykova commented on Task_2_3_1/src/main/java/fxlab/snake/Point.java
это вроде тоже часть модели

2024-05-08 02:38 UTC, AntonTsoy commented on Task_2_3_1/src/main/java/fxlab/snake/Point.java
перенес в папку Model

2024-05-08 03:28 UTC, merged