Task_2_1_2
AntonTsoy/OOP pull request #22
Opened 2024-06-03 10:37 UTC by AntonTsoy

2024-06-03 14:58 UTC, galinabykova requested changes
все основные штуки по функциональности у тебя есть, жду тесты)

2024-06-03 14:58 UTC, galinabykova commented on Task_2_1_2/src/main/java/network/Client.java
> +    @SuppressWarnings("deprecation")
а почему вот эта аннотация?

2024-06-03 14:58 UTC, galinabykova commented on Task_2_1_2/src/main/java/network/Server.java
вот тут мне кажется, было бы хорошо разбить на методы приватные, потому что сейчас методы большие и неудобно читать. Исправлять не надо, просто делюсь ощущениями)

2024-06-03 15:16 UTC, AntonTsoy commented on Task_2_1_2/src/main/java/network/Server.java
я увидел этот комментарий только сейчас (когда уже пофиксил этот момент - я сам считал код неудобочитаемым, поэтому прежде чем писать тесты, решил исправить эту проблему)

2024-06-03 15:22 UTC, AntonTsoy commented on Task_2_1_2/src/main/java/network/Client.java
> +    @SuppressWarnings("deprecation")
у меня VS Code ругается на то, что методы leaveGroup и joinGroup - deprecated. Я использую старые версии этих методов, в документации есть новые, но они мне кажутся менее удобными.

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/MulticastSocket.html

2024-06-04 03:55 UTC, galinabykova approved these changes

2024-06-04 04:12 UTC, merged